apiVersion: batch/v1 
kind: Job
metadata:
  name: airflow-upgradedb-1.8.0.alpha.10
  namespace: default
spec:
  template:
    metadata:
      name: airflow-initdb
    spec:
      volumes:
      - name: airflow-home
        emptyDir: {}
      - name: service-account
        secret:
          secretName: "service-account"
      - name: ssl-certs
        hostPath:
          path: /etc/ssl/certs
      - name: airflow-config
        configMap:
          name: airflow-config
      containers:
      - image: b.gcr.io/airflow-gcp/airflow-base:1.8.0.alpha.1
        imagePullPolicy: IfNotPresent
        command: ["airflow", "upgradedb"]
        name: airflow-initdb 
        env:
        - name: AIRFLOW_HOME
          value: /etc/airflow
        volumeMounts:
        - name: airflow-home
          mountPath: /home/airflow
        - name: airflow-config
          mountPath: /etc/airflow
        - name: service-account
          mountPath: /secret
        - name: ssl-certs
          mountPath: /etc/ssl/certs
      dnsPolicy: ClusterFirst
      restartPolicy: Never 
      securityContext: {}
      terminationGracePeriodSeconds: 30
