apiVersion: v1
kind: Service
metadata:
  labels:
    run: airflow-db 
  name: airflow-db
  namespace: default
spec:
  ports:
  - port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    run: airflow-db 
  sessionAffinity: None
  type: ClusterIP
