apiVersion: v1
kind: Service
metadata:
  labels:
    run: airflow
  name: airflow
  namespace: default
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    run: airflow-webserver
  sessionAffinity: None
  type: LoadBalancer
